		//OPTRE
		class handgunshaloFC{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_handguns"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\handgun_ca.paa";

			ITEM(OPTRE_FC_Plasma_Pistol, 250, PISTOL_STOCK);
			ITEM(OPTRE_FC_T25_Rifle_Folded, 350, PISTOL_STOCK);
			ITEM(OPTRE_FC_T25J_Rifle_Folded, 375, PISTOL_STOCK);
		};

		class smghaloFC{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_smgs"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";

			ITEM(OPTRE_FC_Needler, 1000, RIFLE_STOCK);
		};

		class rifleshaloFC{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_rifles"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";
			// Covenant
			ITEM(OPTRE_FC_T25_Rifle, 600, RIFLE_STOCK);
			ITEM(OPTRE_FC_T25J_Rifle, 700, RIFLE_STOCK);
			
			ITEM(OPTRE_FC_T51_Repeater, 600, RIFLE_STOCK);
			ITEM(OPTRE_FC_T51J_Repeater, 1100, RIFLE_STOCK);
			
			ITEM(OPTRE_FC_T60_PulseCarbine, 600, RIFLE_STOCK);
			ITEM(OPTRE_FC_T50_SRS, 2000, RIFLE_STOCK);
		};

		class sniperrifleshaloFC{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_sniperRifles"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";

			ITEM(OPTRE_FC_T31_NeedleRifle 1000, RIFLE_STOCK);
			ITEM(OPTRE_FC_T50_SRS, 1000, RIFLE_STOCK);
			ITEM(OPTRE_FC_T51_Carbine, 1100, RIFLE_STOCK);
			ITEM(OPTRE_FC_T51B_Carbine, 1500, RIFLE_STOCK);
		};

		class launchershaloFC{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_launchers"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\secondaryWeapon_ca.paa";
			ITEM(OPTRE_FC_T33_FuelRod_Cannon_Guided, 500, 25); 
			ITEM(OPTRE_FC_T33_FuelRod_Cannon, 500, 25);
		}; 

		class launchermagazineshaloFC{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_launcherAmmo"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\cargoMag_ca.paa";
			ITEM(OPTRE_FC_T33_FuelRod_Pack_Guided, 300, 15);
			ITEM(OPTRE_FC_T33_FuelRod_Pack, 200, 15);
		};

		class specialweaponshaloFC{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_specialWeapons"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";

			ITEM(OPTRE_FC_Jackal_Shield, 1500, RIFLE_STOCK);
			ITEM(OPTRE_FC_Jackal_Shield_Needler, 2000, RIFLE_STOCK);
			ITEM(OPTRE_FC_Jackal_Orange_Shield_Needler, 2000, RIFLE_STOCK);
			ITEM(OPTRE_FC_Jackal_Red_Shield_Needler, 2000, RIFLE_STOCK);
			ITEM(OPTRE_FC_Jackal_Orange_Shield, 1500, RIFLE_STOCK);
			ITEM(OPTRE_FC_Jackal_Red_Shield, 1500, RIFLE_STOCK);
			ITEM(OPTRE_FC_T50_ConcussionRifle, 1000, RIFLE_STOCK);
			ITEM(OPTRE_FC_Railgun, 15000, RIFLE_STOCK);
		};

		class magazineshaloFC{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_magazines"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\cargoMag_ca.paa";
			
			ITEM(OPTRE_FC_Plasma_Pistol_Battery, 100, MZ_STOCK);
            ITEM(OPTRE_FC_T25_Rifle_Battery, 100, MZ_STOCK);
            ITEM(OPTRE_FC_T25J_Rifle_Battery, 100, MZ_STOCK);
			ITEM(OPTRE_FC_Needler_Mag, 200, MZ_STOCK);
			ITEM(OPTRE_FC_NeedleRifle_Mag, 200, MZ_STOCK);
			ITEM(OPTRE_FC_T50_6rnd_mag, 500, MZ_STOCK);
			ITEM(OPTRE_FC_T50_SRS_Battery, 1000, MZ_STOCK);
			ITEM(OPTRE_FC_T51_Ammo_Cartridge, 150, MZ_STOCK);
			ITEM(OPTRE_FC_T51_Repeater_Battery, 100, MZ_STOCK);
			ITEM(OPTRE_FC_T51J_Repeater_Battery, 150, MZ_STOCK);
			ITEM(OPTRE_FC_Blamite_Mag, 250, MZ_STOCK);
			ITEM(OPTRE_FC_T60_Pulse_Carbine_Battery, 100, MZ_STOCK);
			ITEM(OPTRE_FC_Railgun_Slug, 1000, MZ_STOCK);
		};

		class mischaloFC{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_misc"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";

			// Covenant gear
			ITEM(OPTRE_FC_BubbleShield, 1000, MISC_STOCK);

			ITEM(OPTRE_FC_FuelRod_Mine, 400, MISC_STOCK);
			ITEM(OPTRE_FC_NeedleMine_Dispenser_AntiInfantry, 400, MISC_STOCK);
			ITEM(OPTRE_FC_PlasmaMine, 400, MISC_STOCK);
			ITEM(OPTRE_FC_Ultra_Mine, 400, MISC_STOCK);

			ITEM(OPTRE_FC_PlasmaGrenade, 200, MISC_STOCK);
		};

		class navigationhaloFC
		{
			displayName = __EVAL(formatText ["%1 %2, %3 %4 %5", localize "STR_A3AU_optreFC", localize "STR_A3AU_gps", localize "STR_A3AU_binoculars", localize "STR_A3AU_and", localize "STR_A3AU_nvgs"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\compass_ca.paa";

			ITEM(OPTRE_FC_NVG, 1000, MISC_STOCK);
		};

		class backpackshaloFC
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_backpacks"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";

			ITEM(OPTRE_FC_Gheocin_Combat_Support_Pod, 1000, MISC_STOCK);
			ITEM(OPTRE_FC_Gheocin_Combat_Support_Pod_Spartan, 2000, MISC_STOCK);

			ITEM(OPTRE_FC_Gheocin_Combat_Support_Pod_Orange, 1000, MISC_STOCK);
			ITEM(OPTRE_FC_Gheocin_Combat_Support_Pod_Spartan_Orange, 2000, MISC_STOCK);

			ITEM(OPTRE_FC_Gheocin_Combat_Support_Pod_Red, 1000, MISC_STOCK);
			ITEM(OPTRE_FC_Gheocin_Combat_Support_Pod_Spartan_Red, 2000, MISC_STOCK);
		};

		class vestshaloFC
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_vests"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";

			ITEM(OPTRE_V_Jackal_vest, 600, MISC_STOCK);
			ITEM(OPTRE_V_Jackal_Bracer_vest, 650, MISC_STOCK);
			ITEM(OPTRE_V_Jackal_gold_vest, 600, MISC_STOCK);
			ITEM(OPTRE_V_Jackal_red_vest, 600, MISC_STOCK);

			ITEM(OPTRE_FC_M52B_Armor_Vest, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Vest_DES, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Breacher_DES, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Grenadier_DES, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Light_DES, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Marksman_DES, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Rifleman_DES, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Sniper_DES, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_TeamLeader_DES, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Vest_SNO, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Breacher_SNO, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Grenadier_SNO, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Light_SNO, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Marksman_SNO, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Rifleman_SNO, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Sniper_SNO, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_TeamLeader_SNO, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Vest_URB, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Breacher_URB, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Grenadier_URB, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Light_URB, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Marksman_URB, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Rifleman_URB, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Sniper_URB, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_TeamLeader_URB, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Vest_BRN, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Breacher_BRN, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Grenadier_BRN, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Light_BRN, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Marksman_BRN, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Rifleman_BRN, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Sniper_BRN, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_TeamLeader_BRN, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Breacher, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Grenadier, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Light, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Marksman, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Rifleman, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_Sniper, 600, MISC_STOCK);
			ITEM(OPTRE_FC_M52B_Armor_TeamLeader, 600, MISC_STOCK);

			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Human, 5000, MISC_STOCK);
		};

		class uniformshaloFC
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_uniforms"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			
			ITEM(OPTRE_FC_Marines_Uniform, 600, MISC_STOCK);
			ITEM(OPTRE_FC_Marines_Uniform_BLK, 600, MISC_STOCK);
			ITEM(OPTRE_FC_Marines_Uniform_BRN, 600, MISC_STOCK);
			ITEM(OPTRE_FC_Marines_Uniform_DES, 600, MISC_STOCK);
			ITEM(OPTRE_FC_Marines_Uniform_GRN, 600, MISC_STOCK);
			ITEM(OPTRE_FC_Marines_Uniform_SNO, 600, MISC_STOCK);
			ITEM(OPTRE_FC_Marines_Uniform_TRO, 600, MISC_STOCK);
			ITEM(OPTRE_FC_Marines_Uniform_WDL, 600, MISC_STOCK);

			ITEM(OPTRE_FC_Marines_Uniform_L, 600, MISC_STOCK);
			ITEM(OPTRE_FC_Marines_Uniform_BRN_L, 600, MISC_STOCK);
			ITEM(OPTRE_FC_Marines_Uniform_DES_L, 600, MISC_STOCK);
			ITEM(OPTRE_FC_Marines_Uniform_GRN_L, 600, MISC_STOCK);
			ITEM(OPTRE_FC_Marines_Uniform_SNO_L, 600, MISC_STOCK);
			ITEM(OPTRE_FC_Marines_Uniform_TRO_L, 600, MISC_STOCK);
			ITEM(OPTRE_FC_Marines_Uniform_WDL_L, 600, MISC_STOCK);

			ITEM(OPTRE_U_Jackal_uniform, 1000, MISC_STOCK);

			ITEM(OPTRE_UNSC_MJOLNIR_MKVI_Undersuit_Human, 3000, MISC_STOCK);

			ITEM(OPTRE_FC_MJOLNIR_MKVI_Undersuit, 5000, MISC_STOCK);

			ITEM(OPTRE_FC_Elite_CombatSkin, 5000, MISC_STOCK);
		};

		class helmetshaloFC
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_helmets"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			///////helmets
			
			ITEM(OPTRE_FC_Elite_Helmet_Officer, 1400, MISC_STOCK);
			ITEM(OPTRE_FC_Elite_Helmet_Minor, 1400, MISC_STOCK);
			ITEM(OPTRE_FC_Elite_Helmet_SpecOps, 1600, MISC_STOCK);
			ITEM(OPTRE_FC_Elite_Helmet_Ultra, 1600, MISC_STOCK);
			ITEM(OPTRE_FC_Elite_Helmet_Zealot, 1600, MISC_STOCK);
			ITEM(OPTRE_FC_Elite_Helmet_Major, 1600, MISC_STOCK);
			ITEM(OPTRE_FC_Elite_Helmet_HonorGuard, 1600, MISC_STOCK);
			ITEM(OPTRE_FC_Elite_Helmet_HonorGuard_Ultra, 1800, MISC_STOCK);
			ITEM(OPTRE_FC_Elite_Helmet_FieldMarshal, 1800, MISC_STOCK);

			ITEM(OPTRE_FC_VX19_Helmet, 600, MISC_STOCK);
			ITEM(OPTRE_FC_VX19_Helmet_Brown, 600, MISC_STOCK);
			ITEM(OPTRE_FC_VX19_Helmet_Desert, 600, MISC_STOCK);
			ITEM(OPTRE_FC_VX19_Helmet_Snow, 600, MISC_STOCK);
			ITEM(OPTRE_FC_VX19_Helmet_Urban, 600, MISC_STOCK);

			ITEM(OPTRE_FC_CH255_Helmet, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_DES, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_DES_Medic, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_Medic, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_SNO, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_SNO_Medic, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_URB, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_URB_Medic, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_BRN, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_BRN_Medic, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_Visor, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_DES_Visor, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_DES_Visor_Medic, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_Visor_Medic, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_SNO_Visor, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_SNO_Visor_Medic, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_URB_Visor_Medic, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_BRN_Visor, 600, MISC_STOCK);
			ITEM(OPTRE_FC_CH255_Helmet_BRN_Visor_Medic, 600, MISC_STOCK);

			ITEM(OPTRE_FC_Jackal_SO_Headgear, 400, MISC_STOCK);
			ITEM(OPTRE_FC_Jackal_T_Headgear, 450, MISC_STOCK);

			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet_Human, 3000, MISC_STOCK);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Helmet_Human, 3000, MISC_STOCK);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Helmet_Human, 3000, MISC_STOCK);
			ITEM(OPTRE_FC_MJOLNIR_MKVI_Helmet_Human, 3000, MISC_STOCK);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Rogue_Helmet_Human, 3000, MISC_STOCK);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Helmet_Human, 3000, MISC_STOCK);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Helmet_Human, 3000, MISC_STOCK);
		};

		class spartanhelmetshaloFC{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_misc"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";

			// Spartan gear
			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet_Freeman, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet_117, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet_Caboose, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet_Church, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet_Donut, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet_Simmons, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet_Night, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet_Grif, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet_Sarge, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Helmet_Tucker, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Olive_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_White_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Black_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Tan_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Olive_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_White_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Black_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Tan_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Caboose, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Lopez, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Church, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Donut, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Simmons, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_North, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Grif, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Doc, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Sarge, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_South, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Tex, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Tucker, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Washington, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Kaikaina, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Helmet_York, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Rogue_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Rogue_Olive_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Rogue_Black_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Rogue_Tan_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Rogue_White_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Olive_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_White_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Black_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Tan_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Olive_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_White_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Black_Helmet, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Tan_Helmet, 5000, 10);
		};

		class spartanarmorhaloFC{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_optreFC", localize "STR_A3AU_spartanarmor"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";

			// Spartan gear
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_EOD_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_EOD_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Mark_VI_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_L_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_R_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_EOD_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_EOD_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Mark_VI_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_L_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_R_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_EOD_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_EOD_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Mark_VI_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_L_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_R_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_EOD_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_EOD_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Mark_VI_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_L_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_R_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_B, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_EOD_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Scout_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Security_R, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_EOD_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Scout_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_L_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_R_Security_L, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Armor, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Armor_117, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Armor_Freeman, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Armor_Caboose, 5000, 10);
    		ITEM(OPTRE_FC_MJOLNIR_MKV_Armor_Church, 5000, 10);
    		ITEM(OPTRE_FC_MJOLNIR_MKV_Armor_Donut, 5000, 10);
    		ITEM(OPTRE_FC_MJOLNIR_MKV_Armor_Simmons, 5000, 10);
    		ITEM(OPTRE_FC_MJOLNIR_MKV_Armor_Night, 5000, 10);
    		ITEM(OPTRE_FC_MJOLNIR_MKV_Armor_Grif, 5000, 10);
    		ITEM(OPTRE_FC_MJOLNIR_MKV_Armor_Sarge, 5000, 10);
    		ITEM(OPTRE_FC_MJOLNIR_MKV_Armor_Tucker, 5000, 10);
			// _Black
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_Black_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_Black_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_Black_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_Black_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Black_EOD_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Black_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Black_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Black_EOD_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Black_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Black_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_L_Black_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_R_Black_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Black_EOD_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Black_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Black_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Black_EOD_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Black_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Black_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_Black_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_Black_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_Black_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_Black_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Mark_VI_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_L_Black_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_R_Black_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Black_EOD_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Black_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Black_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Black_EOD_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Black_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Black_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_Black_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_Black_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_Black_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_Black_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Mark_VI_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_L_Black_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_R_Black_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Black_EOD_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Black_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Black_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Black_EOD_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Black_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Black_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_Black_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_Black_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_Black_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_Black_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Mark_VI_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_L_Black_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_R_Black_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Black_EOD_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Black_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Black_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Black_EOD_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Black_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Black_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_Black_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_Black_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_Black_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_Black_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Mark_VI_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_L_Black_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_R_Black_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_B_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_L_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_R_Black, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Armor_Black, 5000, 10);
			// _Olive
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_Olive_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_Olive_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_Olive_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_Olive_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Olive_EOD_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Olive_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Olive_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Olive_EOD_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Olive_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Olive_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_L_Olive_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_R_Olive_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Olive_EOD_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Olive_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Olive_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Olive_EOD_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Olive_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Olive_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_Olive_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_Olive_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_Olive_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_Olive_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Mark_VI_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_L_Olive_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_R_Olive_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Olive_EOD_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Olive_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Olive_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Olive_EOD_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Olive_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Olive_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_Olive_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_Olive_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_Olive_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_Olive_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Mark_VI_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_L_Olive_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_R_Olive_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Olive_EOD_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Olive_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Olive_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Olive_EOD_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Olive_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Olive_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_Olive_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_Olive_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_Olive_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_Olive_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Mark_VI_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_L_Olive_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_R_Olive_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Olive_EOD_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Olive_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Olive_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Olive_EOD_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Olive_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Olive_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_Olive_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_Olive_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_Olive_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_Olive_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Mark_VI_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_L_Olive_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_R_Olive_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_B_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_L_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_R_Olive, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_MKV_Armor_Olive, 5000, 10);
			// _Tan
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_Tan_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_Tan_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_Tan_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_Tan_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Tan_EOD_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Tan_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_Tan_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Tan_EOD_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Tan_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_Tan_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_L_Tan_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_R_Tan_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Tan_EOD_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Tan_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_Tan_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Tan_EOD_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Tan_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_Tan_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_Tan_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_Tan_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_Tan_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_Tan_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Mark_VI_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_L_Tan_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_R_Tan_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Tan_EOD_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Tan_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_Tan_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Tan_EOD_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Tan_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_Tan_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_Tan_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_Tan_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_Tan_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_Tan_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Mark_VI_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_L_Tan_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_R_Tan_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Tan_EOD_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Tan_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_Tan_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Tan_EOD_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Tan_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_Tan_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_Tan_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_Tan_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_Tan_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_Tan_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Mark_VI_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_L_Tan_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_R_Tan_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Tan_EOD_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Tan_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_Tan_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Tan_EOD_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Tan_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_Tan_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_Tan_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_Tan_Security_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_Tan_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_Tan_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Mark_VI_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_R_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_L_Tan_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_R_Tan_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_B_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_L_Tan, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_R_Tan, 5000, 10);
			//Snow
			ITEM(OPTRE_FC_MJOLNIR_MKV_Armor_Night, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_White_EOD_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_White_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_White_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_White_EOD_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_White_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_White_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Mark_VI_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_White_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_White_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_L_White_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EOD_R_White_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_EVA_R_White_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Scout_R_White_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EOD_Armor_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_White_EOD_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_White_EOD_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_White_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_White_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_White_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_White_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_White_EOD_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_White_EOD_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_White_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_White_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_White_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_White_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Mark_VI_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_White_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_White_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_White_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_White_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_L_White_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_L_White_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_R_White_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EOD_R_White_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_R_White_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_EVA_R_White_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_R_White_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Scout_R_White_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_EVA_Armor_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EOD_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_EVA_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_White_EOD_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_White_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_White_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_White_EOD_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_White_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_White_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Mark_VI_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_White_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_White_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_L_White_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EOD_R_White_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_EVA_R_White_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Scout_R_White_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Scout_Armor_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Scout_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_White_EOD_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_White_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_White_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_White_EOD_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_White_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_White_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Mark_VI_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_White_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_White_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_L_White_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EOD_R_White_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_EVA_R_White_Security, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Scout_R_White_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_B_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_L_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Security_Armor_Security_R_White, 5000, 10);
			ITEM(OPTRE_FC_MJOLNIR_Mark_VI_Armor_Security_White, 5000, 10);
		};
