		class handgunsspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_handguns"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\handgun_ca.paa";
			
			ITEM(SPEX_Enfield_No2, 80, PISTOL_STOCK); //AMMO: SPEX_6rnd_9x20R
			ITEM(SPEX_Enfield_No2_late, 80, PISTOL_STOCK); //AMMO: SPEX_6rnd_9x20R
			
		};

		class smgspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_smgs"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";
		
			ITEM(SPEX_Owen_Gun, 165, RIFLE_STOCK); // SPE_32Rnd_9x19_Owen
			ITEM(SPEX_Owen_Gun_Camo, 170, RIFLE_STOCK); // SPE_32Rnd_9x19_Owen
			ITEM(SPEX_Sten_Mk5, 200, RIFLE_STOCK); // SPE_32Rnd_9x19_Sten
			ITEM(SPEX_Sten_Mk6_Suppressed, 400, RIFLE_STOCK); // SPE_32Rnd_9x19_Sten
			ITEM(SPEX_M1928_Thompson, 300, RIFLE_STOCK); // SPEX_50Rnd_Thompson_45ACP SPEX_50Rnd_Thompson_45ACP_t 
			ITEM(SPEX_M1928A1_Thompson, 300, RIFLE_STOCK); // SPEX_50Rnd_Thompson_45ACP SPEX_50Rnd_Thompson_45ACP_t 
		};

		class riflesspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_rifles"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";

			ITEM(SPEX_No1_Mk3_Enfield, 210, RIFLE_STOCK); //NORMAL: SPE_5Rnd_770x56 SPE_5Rnd_770x56_AP_MKI SPE_5Rnd_770x56_MKVIII
			ITEM(SPEX_No1_Mk3_mid_Enfield, 210, RIFLE_STOCK); //NORMAL: SPE_5Rnd_770x56 SPE_5Rnd_770x56_AP_MKI SPE_5Rnd_770x56_MKVIII
			ITEM(SPEX_No1_Mk3_late_Enfield, 210, RIFLE_STOCK); //NORMAL: SPE_5Rnd_770x56 SPE_5Rnd_770x56_AP_MKI SPE_5Rnd_770x56_MKVIII
			ITEM(SPEX_No4_Mk1_Enfield, 230, RIFLE_STOCK); //NORMAL: SPE_5Rnd_770x56 SPE_5Rnd_770x56_AP_MKI SPE_5Rnd_770x56_MKVIII
			ITEM(SPEX_No4_Mk1_Enfield_dunkel, 230, RIFLE_STOCK); //NORMAL: SPE_5Rnd_770x56 SPE_5Rnd_770x56_AP_MKI SPE_5Rnd_770x56_MKVIII
		};

		class mgspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_mgs"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";	

			ITEM(SPEX_LMG_303_Mk1, 380, RIFLE_STOCK); // SPE_30Rnd_770x56 SPE_30Rnd_770x56_AP_MKI SPE_30Rnd_770x56_MKVIII
			
		};

		class sniperriflesspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_sniperRifles"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\primaryWeapon_ca.paa";
		
			ITEM(SPEX_No4_Mk1_Enfield_Scoped, 570, RIFLE_STOCK); // SAME AS SPE_M1903A3_Springfield
			ITEM(SPEX_No4_Mk1_Enfield_Scoped_dunkel, 570, RIFLE_STOCK); // SAME AS SPE_M1903A3_Springfield
			ITEM(SPEX_No4_Mk1_Enfield_Scoped, 570, RIFLE_STOCK); // SAME AS SPE_M1903A3_Springfield
		};
		
		class launchersspex
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_launchers"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\secondaryWeapon_ca.paa";

			ITEM(SPEX_M2_60_Barrel, 1000, 15);
			ITEM(SPEX_M2_60_Stand, 1000, 15); 

			ITEM(SPEX_2_Inch_Mk7_Mortar_Slung, 1000, 15);

			ITEM(SPEX_PIAT, 350, 15);
			ITEM(SPEX_PIAT_Brown, 350, 15);

		}; 

		class launchermagazinesspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_launcherAmmo"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\cargoMag_ca.paa";

			ITEM(SPEX_1Rnd_89mm_PIAT, 100, 15);
			
		};

		class miscspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_misc"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			
			ITEM(SPEX_PIAT_Sleeve, 50, MISC_STOCK);

			ITEM(SPEX_ACC_Enfield_No1_Wires, 50, MISC_STOCK);
			
		};

		class muzzlesspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spearhead", localize "STR_A3AU_muzzles"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\itemMuzzle_ca.paa";
			
			ITEM(SPEX_ACC_2HalfInch_GL_CUP, 75, MZ_STOCK);
			ITEM(SPEX_ACC_P1907_Bayo, 75, MZ_STOCK);

			ITEM(SPEX_ACC_No4_Mk2_Bayo, 75, MZ_STOCK);

			ITEM(SPEX_ACC_No4_Mk2_Bayo, 75, MZ_STOCK);
			
		};

		class magazinesspe{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_magazines"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\cargoMag_ca.paa";		
			
			ITEM(SPEX_6rnd_9x20R, 10, MZ_STOCK);

			ITEM(SPEX_50Rnd_Thompson_45ACP, 50, MZ_STOCK);
			ITEM(SPEX_50Rnd_Thompson_45ACP_t, 50, MZ_STOCK);
			
			ITEM(SPEX_10Rnd_770x56, 40, MZ_STOCK);
			ITEM(SPEX_10Rnd_770x56_AP_MKI, 30, MZ_STOCK);
			ITEM(SPEX_10Rnd_770x56_MkVIII, 30, MZ_STOCK);
		};


		class helmetsspex 
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_helmets"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			/////helmets
			ITEM(H_SPE_US_AB_Helmet_327_CO_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_NCO_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_Scrim_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_CO_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_CO_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_NCO_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_Net_up, 100, MISC_STOCK);

			ITEM(H_SPE_US_AB_Helmet_327_CO_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_NCO_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_CO_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_Scrim_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_CO_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_NCO_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_NCO_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_Net_up, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_CO_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_NCO_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_Scrim_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_Net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_ns, 100, MISC_STOCK);

			ITEM(H_SPE_US_AB_Helmet_327_polar, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_polar_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_polar_Scrim_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_polar_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_polar_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_polar_net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_polar_net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_polar_net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_polar_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_Scrim_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_os, 100, MISC_STOCK);

			ITEM(H_SPE_US_AB_Helmet_506_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_Net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_Net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_polar, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_polar_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_polar_Scrim_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_polar_Scrim_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_polar_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_polar_net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_polar_net_os, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_polar_net_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_polar_ns, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_CO, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_NCO, 100, MISC_STOCK);

			ITEM(H_SPE_US_AB_Helmet_327_NCO_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_CO_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_327_NCO_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_CO, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_NCO, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_CO_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_NCO_Scrim, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_CO_Net, 100, MISC_STOCK);
			ITEM(H_SPE_US_AB_Helmet_506_NCO_Net, 100, MISC_STOCK);

			//1.2.0 update
			ITEM(H_SPEX_CAN_beret_MAISONNEVUE, 50, MISC_STOCK);
			ITEM(H_SPEX_CAN_beret_PPCLI, 50, MISC_STOCK);
			ITEM(H_SPEX_CAN_beret_QOR, 50, MISC_STOCK);
			ITEM(H_SPEX_CAN_beret_REGINA, 50, MISC_STOCK);
			ITEM(H_SPEX_CAN_beret_WINNIPEG, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_cdo, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_DCLI, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_DCLI_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_durham_green, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_durham, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_durham_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_East_Yorks, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_East_Yorks_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_Essex, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_Essex_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_KRRC, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_KRRC_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_KSLI, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_KSLI_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_ox_bucks, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_ox_bucks_PARA, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_ox_bucks_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_PARA, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_QUEENS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_QUEENS_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_GEWEHR, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_GEWEHR_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_ENG, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_ENG_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_ULSTER, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_ULSTER_PARA, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_ULSTER_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_SOMERSET, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_SOMERSET_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_Welch, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_Welch_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_gs, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_RECCE, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_RECCE_goggle, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_RECCE_no38, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_RECCE_no38_goggle, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_ARTY, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_ARTY_goggle, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_ARTY_GS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_ARTY_no38, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_ARTY_no38_goggle, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_pz, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_pz_goggle, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_pz_no38, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_pz_no38_goggle, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_mutsdas, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_DCLI, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_durham_green, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_durham, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_East_Yorks, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_Essex, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_KRRC, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_KSLI, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_ox_bucks_gewehr, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_ox_bucks, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_QUEENS, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_GEWEHR, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_ENG, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_ULSTER, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_SOMERSET, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_Welch, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP, 50, MISC_STOCK);

			ITEM(H_SPEX_CW_HSAT_mk1, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk1_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk2, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk2_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk2_net, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk2_net_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk2_scrim, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk2_scrim_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk3, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk3_net, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk3_scrim, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk1_net, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk1_net_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk1_scrim, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_HSAT_mk1_scrim_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_burlap, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_burlap_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_burlap_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_burlap_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_desert, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_desert_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_desert_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_desert_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_desert_net, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_desert_net_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_desert_net_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_desert_net_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_ifak, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_ifak_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_ifak_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_ifak_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_hessian, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_hessian_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_hessian_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_hessian_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_net, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_net_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_net_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_net_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_scrim, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_scrim_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_scrim_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_scrim_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_scrim_ifak, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_scrim_ifak_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_scrim_ifak_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk2_scrim_ifak_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3_ifak, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3_ifak_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3_ifak_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3_ifak_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3_net, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3_net_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3_scrim, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3_scrim_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3_scrim_ifak, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3_scrim_ifak_op, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3_scrim_ifak_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_mk3_scrim_ifak_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_RAC, 100, MISC_STOCK);
			ITEM(H_SPEX_CW_Helmet_RAC_no38, 100, MISC_STOCK);

			ITEM(H_SPEX_CW_hat_felt, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_hat_felt_cl, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_hat_felt_slouch, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_hat_felt_slouch_cl, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_RAF_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_SIDECAP_RAF_EM, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_RAF_visor_EM, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_RAF_visor, 50, MISC_STOCK);
			ITEM(H_SPEX_CW_beret_cdo_FR, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_PITH_LW_blau, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_PITH_LW_blau_OP, 50, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_CAP_TROP, 50, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_CAP_TROP_ROMMEL, 50, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_CAP_TROP_HP_ROMMEL, 50, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_CAP_TROP_HP, 50, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_CAP_TROP_ROMMEL_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_CAP_TROP_HP_ROMMEL_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_CAP_TROP_HP_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_CAP_TROP_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_PITH_LW, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_PITH_LW_OP, 50, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_SIDECAP, 50, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_SIDECAP_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_SIDECAP_2_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_SIDECAP_2, 50, MISC_STOCK);

			ITEM(H_SPEX_LW_DAK_Helmet_M35_3, 100, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_Helmet_M35_Utility, 100, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_Helmet_M35_Utility_ns, 100, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_Helmet_M35, 100, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_Helmet_M35_Glasses, 100, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_Helmet_M35_Glasses_ns, 100, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_Helmet_M35_ns, 100, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_Helmet_M35_2_ns, 100, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_Helmet_M35_3_ns, 100, MISC_STOCK);
			ITEM(H_SPEX_LW_DAK_Helmet_M35_2, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_VISOR_ART_OFFZ_ROMMEL, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_VISOR_ART_UFFZ_ROMMEL, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_VISOR_INF_OFFZ_ROMMEL, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_VISOR_INF_UFFZ_ROMMEL, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_VISOR_PZGREN_OFFZ_ROMMEL, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_VISOR_PZGREN_UFFZ_ROMMEL, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_VISOR_PZ_HP_OFFZ_ROMMEL, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_VISOR_PZ_HP_UFFZ_ROMMEL, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_VISOR_PZ_OFFZ_ROMMEL, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_VISOR_PZ_UFFZ_ROMMEL, 100, MISC_STOCK);

			ITEM(H_SPEX_GER_Helmet_chute_band, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_Helmet_chute_band_ns, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_Helmet_chute, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_Helmet_chute_OS, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_ART_HP, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_ART_HP_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_ART_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_ART, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_ROMMEL, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_HP_ROMMEL, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_HP, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_INF_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_INF, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_ROMMEL_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_HP_ROMMEL_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_HP_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_PZ_ROMMEL, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_PZ_HP_ROMMEL, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_PZ_HP, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_PZ_OFFZ_ROMMEL, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_PZ_HP_OFFZ_ROMMEL, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_PZ_HP_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_PZ_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_PZ, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_PZGREN_OFFZ, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_CAP_TROP_PZGREN, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_PITH, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_PITH_HEER, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_PITH_HEER_OP, 50, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_PITH_OP, 50, MISC_STOCK);

			ITEM(H_SPEX_GER_DAK_Helmet_M35, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_Helmet_M35_Utility, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_Helmet_M35_Utility_ns, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_Helmet_M35_Glasses, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_Helmet_M35_Glasses_ns, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_Helmet_M35_ns, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_Helmet_M40, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_Helmet_M40_Utility, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_Helmet_M40_Utility_ns, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_Helmet_M40_Glasses, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_Helmet_M40_Glasses_ns, 100, MISC_STOCK);
			ITEM(H_SPEX_GER_DAK_Helmet_M40_ns, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_2A, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_2A_op, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_2A_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_2A_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_2A_ifak, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_2A_ifak_op, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_2A_ifak_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_2A_ifak_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_2A_net, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_2A_net_op, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_2A_net_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_2A_net_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_RAC_2A, 100, MISC_STOCK);

			ITEM(H_SPEX_PL_beret_panc, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_beret_panc_goggle, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_beret_panc_no38, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_beret_panc_no38_goggle, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_beret_cdo, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_SIDECAP, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_beret_Piech, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk1, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk1_op, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk2, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk2_op, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk2_net, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk2_net_op, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk2_scrim, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk2_scrim_op, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk3, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk3_net, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk3_scrim, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk1_net, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk1_net_op, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk1_scrim, 50, MISC_STOCK);
			ITEM(H_SPEX_PL_HSAT_mk1_scrim_op, 50, MISC_STOCK);

			ITEM(H_SPEX_PL_Helmet_mk2, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_op, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_desert, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_desert_op, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_desert_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_desert_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_desert_net, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_desert_net_op, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_desert_net_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_desert_net_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_ifak, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_ifak_op, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_ifak_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_ifak_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_net, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_net_op, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_net_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_net_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_SBSK, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_SBSK_op, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_SBSK_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_SBSK_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_SBSK_net, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_SBSK_net_op, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_SBSK_net_op_tilt, 100, MISC_STOCK);
			ITEM(H_SPEX_PL_Helmet_mk2_SBSK_net_tilt, 100, MISC_STOCK);
		};

		class uniformsspex
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_uniforms"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			////uniforms
			ITEM(U_SPEX_AUS_JG_Aertex, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_JG_Aertex_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_JG_Aertex_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_long_burma_anklet, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_long_burma_anklet_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_long_burma, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_long_burma_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_HBT_burma, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_HBT_burma_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_HBT_burma_trop, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_HBT_burma_trop_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_short_burma_anklet, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_short_burma_anklet_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_short_burma, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_short_burma_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_short_burma_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_short_burma_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_long_burma_trop, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_long_burma_trop_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_HBT, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_HBT_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_HBT_trop, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_HBT_trop_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_short_anklet, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_short_medic, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_short_anklet_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_short, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_short_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_short_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_short_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_long_anklet, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_long_anklet_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_long, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_long_medic, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_long_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_long_trop, 50, MISC_STOCK);
			ITEM(U_SPEX_AUS_KD_long_trop_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_CSGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_CPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_LCPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_medic, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_medic_sb, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_SGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_INV, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_inv_CSGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_inv_CPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_inv_LCPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_INV_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_inv_SGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_Officer, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_Jerkin_Officer_INV, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_2LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_CSGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_CPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_CPT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_LCPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_medic, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_open, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_medic_sb, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_SGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_INV, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_2LT_INV, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_INV_CSGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_INV_CPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_CPT_INV, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_INV_LCPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_1LT_INV, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_INV_open, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_INV_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CAN_INV_SGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_CSGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_CPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_LCPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_scarf, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_scarf_tail, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_SGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_tail, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_officer, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_officer_tail, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_glider_officer, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_glider_SGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_kd, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_kd_scarf, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_kd_scarf_tail, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_kd_tail, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_kd_officer, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_kd_officer_tail, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_puttee_scarf, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_puttee_scarf_tail, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_puttee_tail, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_puttee_officer, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Denis_puttee_officer_tail, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_2LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_CSGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_CPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_CPT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_LCPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_open, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_SGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_2LT_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_CPT_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_1LT_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_puttee_open, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_P40_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_CSGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_CPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_LCPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_medic, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_medic_sb, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_SGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_dagger, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_dagger_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_Officer, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_Officer_dagger, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_Officer_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_Jerkin_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_2LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CSGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CPT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_LCPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_medic, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_open, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_medic_sb, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_SGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD_long, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD_long_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD_long_open, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD_long_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD_long_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD_long_puttee_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD_long_puttee_open, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD_long_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD_long_trop, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_KD_long_trop_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_dagger, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_2LT_dagger, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_dagger_CSGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_dagger_CPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CPT_dagger, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_dagger_LCPL, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_1LT_dagger, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_dagger_open, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_dagger_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_dagger_SGT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_2LT_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_CPT_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_1LT_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_puttee_open, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_BD_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_JG_Aertex, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_JG_Aertex_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_JG_Aertex_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_JG_Aertex_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_JG_Aertex_puttee_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_JG_Aertex_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_JG_Bush, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_JG_Bush_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_JG_Bush_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_JG_Bush_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_JG_Bush_puttee_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_JG_Bush_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_JG, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_JG_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_JG_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_JG_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long_burma, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long_burma_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long_burma_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long_burma_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long_burma_trop, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long_burma_trop_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_BD, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_BD_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_BD_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_BD_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_BD, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_BD_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_BD_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_BD_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_BD_puttee_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_BD_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_short, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_short_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_short_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_short_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_short_puttee_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_short_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_long, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_long_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_long_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_long_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_long_puttee_1LT, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_long_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_long_trop, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_Bush_long_trop_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_full, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_full_medic, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_full_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_full_medic_sb, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_full_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_full_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long_medic, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long_medic_sb, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long_puttee, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long_puttee_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long_trop, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_KD_long_trop_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_RAF_BD, 50, MISC_STOCK);
			ITEM(U_SPEX_CW_RAF_BD_glove, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_gefr, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_gloves, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_pads_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_uffz, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_uffz_gloves, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_uffz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_uffz_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_offz, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_offz_gloves, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_offz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk1_zip_offz_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK_gloves, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK_pads_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK_uffz, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK_uffz_gloves, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK_uffz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK_uffz_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_gloves, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_trop, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_trop_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_pads_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_uffz, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_uffz_gloves, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_uffz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_uffz_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK_offz, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK_offz_gloves, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK_offz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk2_DAK_offz_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_offz, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_offz_gloves, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_offz_gloves_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_Mk3_DAK_offz_pads, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_DAK_Feldbluse, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_DAK_Feldbluse_gefreiter, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_DAK_Feldbluse_leutnant, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_DAK_Feldbluse_medic, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_DAK_Feldbluse_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_DAK_Feldbluse_scarf, 50, MISC_STOCK);
			ITEM(U_SPEX_FSJ_DAK_Feldbluse_uffz, 50, MISC_STOCK);
			ITEM(U_SPEX_LW_DAK_Feldbluse, 50, MISC_STOCK);
			ITEM(U_SPEX_LW_DAK_Feldbluse_gefreiter, 50, MISC_STOCK);
			ITEM(U_SPEX_LW_DAK_Feldbluse_leutnant, 50, MISC_STOCK);
			ITEM(U_SPEX_LW_DAK_Feldbluse_medic, 50, MISC_STOCK);
			ITEM(U_SPEX_LW_DAK_Feldbluse_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_LW_DAK_Feldbluse_scarf, 50, MISC_STOCK);
			ITEM(U_SPEX_LW_DAK_Feldbluse_uffz, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_short, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_short_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_short_high, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_short_high_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_gefreiter, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_medic, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_oberschutze, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_uffz, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_high_breech, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_high_breech_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_soc, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_soc_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_high, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_gefreiter_high, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_medic_high, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_oberschutze_high, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_high_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_uffz_high, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_putti, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_gefreiter_putti, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_oberschutze_putti, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_putti_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_uffz_putti, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_short, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_short_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_short_high, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_short_high_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_gefreiter, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_oberschutze, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_uffz, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_high_breech, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_high_breech_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_soc, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_soc_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_high, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_gefreiter_high, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_oberschutze_high, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_high_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_uffz_high, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_putti, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_gefreiter_putti, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_oberschutze_putti, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_putti_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_M42_uffz_putti, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_ART_Feldbluse_leutnant, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_ART_Feldbluse, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_ART_Feldbluse_gefreiter, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_ART_Feldbluse_uffz, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_hauptmann, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_leutnant, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_Feldbluse_oberleutnant, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_PZ_Feldbluse_leutnant, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_PZ_Feldbluse, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_PZ_Feldbluse_gefreiter, 50, MISC_STOCK);
			ITEM(U_SPEX_DAK_PZ_Feldbluse_uffz, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_P40, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_P40_CHOR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_P40_KPT, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_P40_KAPR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_P40_open, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_P40_PPOL, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_P40_PLUT, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_P40_POR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_P40_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_P40_STRZ, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_CHOR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_KPT, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_KAPR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_open, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_PPOL, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_PLUT, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_POR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_PZ_BD_STRZ, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_CDO_BD_dagger, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_CDO_BD_dagger_CHOR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_CDO_BD_KPT_dagger, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_CDO_BD_dagger_KAPR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_CDO_BD_dagger_open, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_CDO_BD_PPOL_dagger, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_CDO_BD_dagger_PLUT, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_CDO_BD_POR_dagger, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_CDO_BD_dagger_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_CDO_BD_dagger_STRZ, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_P40, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_P40_CHOR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_P40_KPT, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_P40_KAPR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_P40_open, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_P40_PPOL, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_P40_PLUT, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_P40_POR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_P40_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_P40_STRZ, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_CHOR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_KPT, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_KAPR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_open, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_PPOL, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_PLUT, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_POR, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_roll, 50, MISC_STOCK);
			ITEM(U_SPEX_PL_INF_BD_STRZ, 50, MISC_STOCK);
		};

		class vestsspe
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_vests"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			///vests
			ITEM(V_SPEX_CW_Vest_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_bandoleer_2, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_RAF_Schwimm, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_Rifle, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_Rifle_golok, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_Rifle_no1, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_Rifle_no4, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_Rifle_p39, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_Rifle_no1_p39, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_Rifle_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_Rifle_golok_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_Rifle_no1_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_Rifle_no4_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_Rifle_no4_P41_2, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_offz, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_offz_canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_offz_sack, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_rac, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_rac_offz, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_binoc, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_golok, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_golok_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n103_medical, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n103_no1, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n103_no1_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n103_no1_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n103_no4, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n103_no4_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n103_no4_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n103_no4_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_no4_Tin_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_offz_light, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_sten, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_sten_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_sten_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_p39, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_p39_binoc, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_no1_p39, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_no1_p39_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_P41_binoc, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_P41_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N103_golok_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n103_medical_p41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_P41_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_no1_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_no1_P41_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_no4_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_no4_P41_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_no4_P41_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_no4_P41_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_no4_P41_Tin_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_no4_P41_2, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_no4_P41_2_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_sten_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_sten_P41_2, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_sten_P41_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N103_sten_P41_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_Rifle, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_Rifle_golok, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_Rifle_no1, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_Rifle_no4, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_Rifle_p39, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_Rifle_no1_p39, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_Rifle_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_Rifle_golok_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_Rifle_no1_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_Rifle_no4_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_Rifle_no4_P41_2, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_offz, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_offz_canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_offz_sack, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_rac, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_rac_offz, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_binoc, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_golok, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_golok_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n61_medical, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n61_no1, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n61_no1_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n61_no1_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n61_no4, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n61_no4_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n61_no4_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n61_no4_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_no4_Tin_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_offz_light, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n61_sten, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n61_sten_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n61_sten_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_p39, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_p39_binoc, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_no1_p39, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_no1_p39_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_P41_binoc, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_P41_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N61_golok_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n61_medical_p41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_P41_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_no1_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_no1_P41_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_no4_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_no4_P41_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_no4_P41_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_no4_P41_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_no4_P41_Tin_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_no4_P41_2, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_no4_P41_2_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_sten_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_sten_P41_2, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_sten_P41_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N61_sten_P41_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_Rifle, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_Rifle_golok, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_Rifle_no1, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_Rifle_no4, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_Rifle_p39, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_Rifle_no1_p39, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_Rifle_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_Rifle_golok_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_Rifle_no1_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_Rifle_no4_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_Rifle_no4_P41_2, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_offz, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_offz_canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_offz_sack, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_rac, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_rac_offz, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_binoc, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_golok, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_golok_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n97_medical, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n97_no1, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n97_no1_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n97_no1_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n97_no4, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n97_no4_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n97_no4_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n97_no4_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_no4_Tin_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_offz_light, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_sten, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_sten_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_sten_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_p39, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_p39_binoc, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_no1_p39, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_no1_p39_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_P41_binoc, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_P41_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_CW_Vest_P37_N97_golok_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_n97_medical_p41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_P41_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_no1_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_no1_P41_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_no4_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_no4_P41_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_no4_P41_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_no4_P41_Tin, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_no4_P41_Tin_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_no4_P41_2, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_no4_P41_2_bandoleer, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_sten_P41, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_sten_P41_2, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_sten_P41_Canteen, 50, MISC_STOCK);
			ITEM(V_SPEX_cw_vest_p37_N97_sten_P41_Tin, 50, MISC_STOCK);
		};

		class backpacksspe
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_backpacks"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			///backpacks
			ITEM(B_SPEX_CW_Sack_bandoleer_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_bandoleer_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_bandoleer_1_left, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_bandoleer_1_right, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_bandoleer_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_no38, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_no38_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_no38, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_no38_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_no38, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_no38_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_no38, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_no38_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_no38, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_no38_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_no38, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_no38_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_no38, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_no38_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_no38, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_no38_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_no38, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_no38_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_no38, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_no38_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_no38, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_no38_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_no38, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_no38_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_PIAT_gas_assault, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_bandoleer, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_bandoleer_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_bren_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_bren_roll_1_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_bren_roll_1_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_bren_roll_2_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_bren_roll_2_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_bren_roll_3_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_bren_roll_3_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_bren_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_shovel, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_assault_shovel_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_dday_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_bren_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_bren_roll_1_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_bren_roll_1_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_bren_roll_2_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_bren_roll_2_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_bren_roll_3_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_bren_roll_3_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_bren_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_shovel, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_DDay_shovel_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_mk5, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_mk5_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_mk5_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_mk5_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_mk5_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_gas_mk5_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_bandoleer, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_bandoleer_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_bren_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_bren_roll_1_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_bren_roll_1_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_bren_roll_2_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_bren_roll_2_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_bren_roll_3_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_bren_roll_3_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_bren_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_shovel, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_shovel_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_bandoleer, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_bandoleer_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_bren_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_bren_roll_1_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_bren_roll_1_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_bren_roll_2_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_bren_roll_2_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_bren_roll_3_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_bren_roll_3_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_bren_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_rope_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_Rope_shovel, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N103_Rope_shovel_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_bandoleer, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_bandoleer_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_bren_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_bren_roll_1_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_bren_roll_1_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_bren_roll_2_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_bren_roll_2_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_bren_roll_3_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_bren_roll_3_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_bren_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_shovel, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_assault_shovel_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_dday_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_bren_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_bren_roll_1_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_bren_roll_1_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_bren_roll_2_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_bren_roll_2_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_bren_roll_3_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_bren_roll_3_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_bren_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_shovel, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_DDay_shovel_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_mk5, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_mk5_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_mk5_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_mk5_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_mk5_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_gas_mk5_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_bandoleer, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_bandoleer_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_bren_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_bren_roll_1_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_bren_roll_1_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_bren_roll_2_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_bren_roll_2_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_bren_roll_3_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_bren_roll_3_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_bren_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_shovel, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_shovel_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_bandoleer, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_bandoleer_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_bren_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_bren_roll_1_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_bren_roll_1_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_bren_roll_2_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_bren_roll_2_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_bren_roll_3_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_bren_roll_3_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_bren_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_rope_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_Rope_shovel, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N61_Rope_shovel_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_bandoleer, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_bandoleer_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_bren_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_bren_roll_1_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_bren_roll_1_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_bren_roll_2_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_bren_roll_2_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_bren_roll_3_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_bren_roll_3_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_bren_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_shovel, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_assault_shovel_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_bren_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_bren_roll_1_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_bren_roll_1_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_bren_roll_2_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_bren_roll_2_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_bren_roll_3_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_bren_roll_3_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_bren_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_shovel, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_DDay_shovel_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_mk5, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_mk5_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_mk5_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_mk5_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_mk5_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_gas_mk5_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_bandoleer, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_bandoleer_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_bren_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_bren_roll_1_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_bren_roll_1_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_bren_roll_2_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_bren_roll_2_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_bren_roll_3_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_bren_roll_3_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_bren_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_shovel, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_shovel_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_bandoleer, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_bandoleer_roll, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_cup, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_PIAT, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_bren_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_bren_roll_1_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_bren_roll_1_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_bren_roll_2_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_bren_roll_2_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_bren_roll_3_front, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_bren_roll_3_side, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_bren_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_roll_1, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_roll_2, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_rope_roll_3, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_Rope_shovel, 50, MISC_STOCK)
			ITEM(B_SPEX_CW_Sack_P37_N97_Rope_shovel_roll, 50, MISC_STOCK)
			///chute
			ITEM(B_SPEX_CW_RAF_Paradrop, 1000, MISC_STOCK)
			ITEM(B_spex_cw_chute_x, 1000, MISC_STOCK)
			ITEM(B_spex_cw_chute_x_dday, 1000, MISC_STOCK)
			ITEM(B_spex_cw_chute_x_mk5, 1000, MISC_STOCK)
			////
			ITEM(B_SPEX_GER_MG_carrier_kit, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_erla_MG_carrier_kit, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_erla_MG_carrier_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_MG_carrier_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_MG_belt_kit, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_erla_MG_belt_kit, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_erla_MG_belt_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_MG_belt_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_MG_Full_kit, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_erla_MG_Full_kit, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_erla_MG_Full_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_MG_Full_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_camo_MG_carrier_kit, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_camo_MG_carrier_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_camo_MG_belt_kit, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_camo_MG_belt_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_camo_MG_Full_kit, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_camo_MG_Full_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_ST_MG_carrier_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_ST_erla_MG_carrier_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_ST_MG_belt_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_ST_erla_MG_belt_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_ST_MG_Full_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_ST_erla_MG_Full_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_ST_camo_MG_carrier_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_ST_camo_MG_belt_zelt, 50, MISC_STOCK)
			ITEM(B_SPEX_GER_ST_camo_MG_Full_zelt, 50, MISC_STOCK)
		};

		class facewearspe
		{
			displayName = __EVAL(formatText ["%1 %2", localize "STR_A3AU_spex", localize "STR_A3AU_facewear"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\backpack_ca.paa";
			///facewear

		};

		class navigationspe
		{
			displayName = __EVAL(formatText ["%1 %2, %3 %4 %5", localize "STR_A3AU_spex", localize "STR_A3AU_gps", localize "STR_A3AU_binoculars", localize "STR_A3AU_and", localize "STR_A3AU_nvgs"]);
			picture = "a3\ui_f\data\gui\Rsc\RscDisplayArsenal\compass_ca.paa";

			ITEM(SPEX_Binocular_CW, 100, NN_STOCK);
			ITEM(SPEX_K35_PH324, 200, NN_STOCK);

			ITEM(SPEX_CW_LE_No4_Signal_Flashlight, 50, NN_STOCK);
			ITEM(SPEX_CW_LE_No4_Signal_Flashlight_SCC1A, 50, NN_STOCK);

		};