////blufor
["EF_B_CombatBoat_Unarmed_GEN", ["armor_front",0.5]],
["EF_B_CombatBoat_AT_NATO", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_B_CombatBoat_Unarmed_NATO", ["armor_front",0.5]],
["EF_B_CombatBoat_HMG_NATO", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_B_CombatBoat_AT_NATO_T", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_B_CombatBoat_Unarmed_NATO_T", ["armor_front",0.5]],
["EF_B_CombatBoat_HMG_NATO_T", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_B_CombatBoat_AT_NATO_Des", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_B_CombatBoat_Unarmed_NATO_Des", ["armor_front",0.5]],
["EF_B_CombatBoat_HMG_NATO_Des", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_B_CombatBoat_AT_CTRG", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_B_CombatBoat_Unarmed_CTRG", ["armor_front",0.5]],
["EF_B_CombatBoat_HMG_CTRG", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_B_MBT_01_mlrs_MJTF_Wdl", ["showCamonetTurret",0.5,"showCamonetHull",0.5]],
["EF_B_AAV9_MJTF_Wdl", ["backpacks",0.3,"camonet_hull",0.3,"camonet_mainTurret",0.3]],
["EF_B_AAV9_50mm_MJTF_Wdl",["backpacks",0.3,"camonet_hull",0.3,"camonet_mainTurret",0.3]],
["EF_B_CombatBoat_AT_MJTF_Wdl", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_B_CombatBoat_Unarmed_MJTF_Wdl", ["armor_front",0.5]],
["EF_B_CombatBoat_HMG_MJTF_Wdl", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_B_MBT_01_TUSK_MJTF_Wdl",["showCamonetTurret",0.3,"showCamonetHull",0.3,"showBags",0.3]],
["EF_B_MBT_01_cannon_MJTF_Wdl",["showBags",0.3,"showCamonetTurret",0.3,"showCamonetHull",0.3]],
["EF_B_MBT_01_mlrs_MJTF_Des",["showCamonetTurret",0.5,"showCamonetHull",0.5]],
["EF_B_AAV9_MJTF_Des", ["backpacks",0.3,"camonet_hull",0.3,"camonet_mainTurret",0.3]],
["EF_B_AAV9_50mm_MJTF_Des",["backpacks",0.3,"camonet_hull",0.3,"camonet_mainTurret",0.3]],
["EF_B_CombatBoat_AT_MJTF_Des", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_B_CombatBoat_Unarmed_MJTF_Des", ["armor_front",0.5]],
["EF_B_CombatBoat_HMG_MJTF_Des", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_B_MBT_01_TUSK_MJTF_Des", ["showCamonetTurret",0.3,"showCamonetHull",0.3,"showBags",0.3]],
["EF_B_MBT_01_cannon_MJTF_Des",[ "showBags",0.3,"showCamonetTurret",0.3,"showCamonetHull",0.3]],
["EF_B_Gyra_Armed_BLU", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_Gyra_Mortar_BLU", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_Gyra_HMG_BLU", ["mg_armor",0.3,"mg_turret_armor",0.3,"tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_Gyra_Antiair_BLU", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_Gyra_BLU", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_T_Gyra_Armed_BLU", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_T_Gyra_Mortar_BLU", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_T_Gyra_HMG_BLU", ["mg_armor",0.3,"mg_turret_armor",0.3,"tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_T_Gyra_Antiair_BLU", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_T_Gyra_BLU", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_ION_Gyra_Armed", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_ION_Gyra_Mortar", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_ION_Gyra_HMG", ["mg_armor",0.3,"mg_turret_armor",0.3,"tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_ION_Gyra_Antiair", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_ION_Gyra", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_Gyra_Armed_UNA", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_Gyra_Mortar_UNA", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_Gyra_HMG_UNA", ["mg_armor",0.3,"mg_turret_armor",0.3,"tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_Gyra_Antiair_UNA", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_Gyra_UNA", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_B_Gyra_HMG_GEN", ["mg_armor",0.3,"mg_turret_armor",0.3,"tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0]],
["EF_B_Gyra_GEN", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0]],
//////opfor
["EF_O_CombatBoat_AT_OPF_R", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_O_CombatBoat_Unarmed_OPF_R", ["armor_front",0.5]],
["EF_O_CombatBoat_HMG_OPF_R", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_O_CombatBoat_AT_OPF", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_O_CombatBoat_Unarmed_OPF", ["armor_front",0.5]],
["EF_O_CombatBoat_HMG_OPF", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_O_CombatBoat_AT_OPF_T", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_O_CombatBoat_Unarmed_OPF_T", ["armor_front",0.5]],
["EF_O_CombatBoat_HMG_OPF_T", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_O_Gyra_Armed_OPF", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_Mortar_OPF", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_HMG_OPF", ["mg_armor",0.3,"mg_turret_armor",0.3,"tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_Antiair_OPF", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_OPF", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_Armed_OPF_T", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_Mortar_OPF_T", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_HMG_OPF_T", ["mg_armor",0.3,"mg_turret_armor",0.3,"tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_Antiair_OPF_T", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_OPF_T", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_Armed_SFIA", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_Mortar_SFIA", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_HMG_SFIA", ["mg_armor",0.3,"mg_turret_armor",0.3,"tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_Antiair_SFIA", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
["EF_O_Gyra_SFIA", ["tools_source",0.3,"bags_source",0.3,"shield_1",0.3,"camonet_hull",0.3]],
///////indep
["EF_I_CombatBoat_AT_AAF", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]],
["EF_I_CombatBoat_Unarmed_AAF", ["armor_front",0.5]],
["EF_I_CombatBoat_HMG_AAF", ["armor_front",0.5,"armor_mid",0.5,"armor_rear",0.5,"mg2_turret_armor",0.5,"mg3_turret_armor",0.5,"mg4_turret_armor",0.5,"mg5_turret_armor",0.5]]