class vehicles_spex : vehicles_base
{
    ITEM(SPEX_LCVP, 5250, "BOAT", VEHICLE_CONDITION_BOAT);
    ITEM(SPEX_HORSA, 13100, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(SPEX_HORSA_MK2, 8300, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(SPEX_C47_Skytrain, 16600, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(SPEX_CG4_WACO, 9500, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(SPEX_GC4_WACO_Cargo, 5600, "PLANE", VEHICLE_CONDITION_PLANE);
    ITEM(SPEX_M2_60, 6000, "STATICMORTAR", VEHICLE_CONDITION_STATICMORTAR);
    ITEM(SPEX_T3_Trailer, 612, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(SPEX_T3_Trailer_Ammo, 7250, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(SPEX_T3_Trailer_Fuel, 7250, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(SPEX_T3_Trailer_Repair, 7250, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);

	ITEM(SPEX_ST_Bedford_MWD, 1450, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(SPEX_ST_Bedford_MWD_Ammo, 11350, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(SPEX_ST_Bedford_MWD_Fuel, 7600, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(SPEX_ST_Bedford_MWD_Open, 1450, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(SPEX_ST_Bedford_MWD_Repair, 15100, "UNARMEDCAR", VEHICLE_CONDITION_UNARMEDCAR);

	ITEM(SPEX_CW_Cromwell_Mk5_noinsignia, 33100, "TANK", VEHICLE_CONDITION_TANK);
	ITEM(SPEX_CW_Cromwell_Mk6_noinsignia, 36400, "TANK", VEHICLE_CONDITION_TANK);
	ITEM(SPEX_CW_Sherman_Vc_noinsignia, 40200, "TANK", VEHICLE_CONDITION_TANK);

    ITEM(SPEX_M4A1_75_DV_noinsignia, 40200, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(SPEX_CW_Sherman_I_noinsignia, 40200, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(SPEX_CW_Sherman_I_Early_noinsignia, 40200, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(SPEX_CW_Sherman_I_Hybrid_noinsignia, 40200, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(SPEX_CW_Sherman_Ic_noinsignia, 40200, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(SPEX_CW_Sherman_Ic_Hybrid_noinsignia, 40200, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(SPEX_CW_Sherman_II_late_noinsignia, 40200, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(SPEX_CW_Sherman_II_Early_noinsignia, 40200, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(SPEX_CW_Sherman_V_noinsignia, 40200, "TANK", VEHICLE_CONDITION_TANK);
    ITEM(SPEX_CW_Sherman_V_Early_noinsignia, 40200, "TANK", VEHICLE_CONDITION_TANK);

	ITEM(SPEX_CW_Humber_MkII_noinsigna, 9100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
	ITEM(SPEX_CW_Humber_LRC_noinsigna, 3100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
	ITEM(SPEX_CW_Humber_MkIV_noinsignia, 14100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);
	ITEM(SPEX_CW_Humber_MkIV_PLM_noinsignia, 14100, "ARMEDCAR", VEHICLE_CONDITION_ARMEDCAR);

    ITEM(SPEX_SBML_2_Inch_Mk7, 3000, "STATICMORTAR", VEHICLE_CONDITION_STATICMORTAR);

    ITEM(SPEX_CW_QF_6_Pounder, 5500, "STATICAT", VEHICLE_CONDITION_STATICAT);
};
